apiVersion: monitoring.coreos.com/v1  
kind: ServiceMonitor
metadata:
  name: askmydocs-api-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - askmydocs   

  selector:
    matchLabels:
      app: askmydocs-api

  endpoints:
    - port: metrics    
      path: /metrics    
      interval: 15s     
      scrapeTimeout: 10s
