apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: askmydocs
spec: 
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: askmydocs
spec:
   selector:
    app: postgres
   clusterIP: None
   ports:
    - port: 5432
